spring:
  datasource:
    url: jdbc:mysql://${ENDPOINT}:3306/book?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    encoding: UTF-8
    url: jdbc:mysql://${ENDPOINT}:3306/book?useSSL=false
    user: root
    password: root